I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 94, in script
    with pause(2)
  File "game/script.rpy", line 94, in <module>
    with pause(2)
NameError: name 'pause' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 94, in script
    with pause(2)
  File "/Applications/renpy-7.4.11-sdk/renpy/ast.py", line 1436, in execute
    trans = renpy.python.py_eval(self.expr)
  File "/Applications/renpy-7.4.11-sdk/renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-7.4.11-sdk/renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 94, in <module>
    with pause(2)
NameError: name 'pause' is not defined

Darwin-21.1.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
IDP2022 1.0
Thu May 12 10:52:00 2022
