I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 390, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 317, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
Exception: DirectSoundCreate8: No audio device found

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/main.py", line 662, in main
    run(restart)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/execution.py", line 922, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00gltest.rpy", line 390, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 317, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/core.py", line 3286, in interact
    self.start()
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/display/core.py", line 2200, in start
    renpy.audio.audio.init()
  File "C:\Users\zerog\Downloads\renpy-7.4.11-sdk/renpy/audio/audio.py", line 955, in init
    renpysound.init(renpy.config.sound_sample_rate, 2, bufsize, False, renpy.config.equal_mono)
  File "renpysound.pyx", line 390, in renpy.audio.renpysound.init
  File "renpysound.pyx", line 98, in renpy.audio.renpysound.check_error
Exception: DirectSoundCreate8: No audio device found

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
IDP2022 1.0
Tue May 24 08:48:08 2022
